[package]

name = "capnpc"
version = "0.0.4"
authors = [ "David Renshaw <david@sandstorm.io>" ]
license = "MIT"
description = "Cap'n Proto schema compiler plugin"
repository = "https://github.com/dwrensha/capnpc-rust"

readme = "README.md"


[lib]

name = "capnpc"
path = "src/lib.rs"


[[bin]]

name = "capnpc-rust"
path = "src/main.rs"


[dependencies]
capnp = "0.0.4"


