[package]

name = "capnpc"
version = "0.1.27"
authors = [ "David Renshaw <david@sandstorm.io>" ]
license = "MIT"
description = "Cap'n Proto schema compiler plugin"
repository = "https://github.com/dwrensha/capnpc-rust"
documentation = "http://docs.capnproto-rust.org"

readme = "README.md"

keywords = ["encoding", "protocol", "serialization"]

[lib]

name = "capnpc"
path = "src/lib.rs"


[[bin]]

name = "capnpc-rust"
path = "src/main.rs"


[dependencies]
capnp = "0.1.27"
